"""Base strategy interface and Signal dataclass."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Signal:
    """A trade signal generated by a strategy."""
    strategy: str
    symbol: str
    direction: str          # "SELL" for short options, "BUY" for equity
    entry_price: float
    stop_loss: float
    target: float
    lot_size: int
    margin_required: float
    confidence: float       # 0.0 to 1.0
    reasoning: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    @abstractmethod
    def generate_signals(self, data: dict) -> list[Signal]:
        """Analyze market data and return trade signals."""
        pass

    @abstractmethod
    def should_exit(self, position, current_data: dict) -> tuple[bool, str]:
        """Check if an open position should be closed.

        Returns:
            (should_exit, reason) — reason is empty string if no exit.
        """
        pass
